# docker-compose.yml
version: '3.8'

services:
  titanaxis-db:
    image: mariadb:11.4
    container_name: titanaxis-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root_password_super_secret
      MARIADB_DATABASE: titanaxis_db
      MARIADB_USER: titan_user
      MARIADB_PASSWORD: titanpass
    ports:
      - "3306:3306" # Expõe a porta do container para o seu localhost
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: