package com.titanaxis.model.ai;

public enum Action {
    // Ações de Guia Visual
    GUIDE_NAVIGATE_TO_ADD_LOTE,
    GUIDE_NAVIGATE_TO_ADD_PRODUCT,

    // Ações de Execução Direta
    DIRECT_CREATE_PRODUCT,
    DIRECT_CREATE_CLIENT,
    DIRECT_CREATE_FORNECEDOR,
    DIRECT_CREATE_CATEGORY,
    DIRECT_CREATE_USER,
    DIRECT_UPDATE_PRODUCT,
    DIRECT_ADD_STOCK,
    DIRECT_ADJUST_STOCK,
    DIRECT_GENERATE_SALES_REPORT_PDF,
    START_SALE_FOR_CLIENT,

    // Ações de Navegação e UI
    UI_CHANGE_THEME,
    UI_NAVIGATE,

    // Ações Proativas (para confirmação do utilizador)
    PROACTIVE_SUGGEST_ADD_LOTE,
    PROACTIVE_SUGGEST_START_SALE,
    PROACTIVE_SUGGEST_CREATE_PURCHASE_ORDER, // NOVO

    // Ação especial
    AWAITING_INFO,
    DISPLAY_COMPLEX_RESPONSE
}